import torch
from attrs import define
from torch import Tensor


@define
class Gaussian:
    """https://en.wikipedia.org/wiki/Additive_white_Gaussian_noise"""

    stdev: float

    def __call__(self, action: Tensor) -> Tensor:
        return torch.randn_like(action) * self.stdev


class OrnsteinUhlenbeck:
    """
    It stabilises zero-mean Gaussian Noise.
    It helps agent explore better in an inertial system.
    Don't abuse Ornstein-Uhlenbeck Process. It has too much hyperparameters and over fine-tuning make no sense.
    """

    def __init__(self) -> None:
        raise NotImplementedError

    def __call__(self, action: Tensor) -> Tensor:
        """Output noise generated by Ornstein-Uhlenbeck Process"""
        raise NotImplementedError
